[build]
  command = "npm install && npx prisma generate"
  functions = "netlify/functions"
  publish = "public"
  package = "@netlify/plugin-cache-clear"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200